# _config.yml

# Theme configuration (modify to match your theme)
theme: jekyll-theme-minimal

# Site title
title: DRAKKAR the ALBUM

# Site description
description: |
  About
  drakkar by nixe! dives into the shadows of heartbreak, wealth, and self-destruction. Inspired by Drakkar Noir, it reflects on identity, depression, and pain. Releasing the night before Valentine’s Day, it questions: will you embrace love or remain in the dark? A raw journey of struggle, change, and the vampiric allure of a dark lifestyle.

  Album Description:
  DRAKKAR is an odyssey through the shadows, a soundtrack for the restless souls caught between pain and ambition, love and despair. Inspired by the dark allure of Drakkar Noir—the cologne that signifies more than its scent—this album dives deep into the struggles that define us. It’s about the cost of identity, where the name on the label matters more than the essence within, reflecting a world obsessed with image over truth.

  Each track captures the raw emotion of navigating wealth, heartbreak, and self-destruction while embracing a vampiric edge—dripping in the mystery and decadence of a Playboi Carti or Destroy Lonely lifestyle. It’s the night before Valentine’s Day, a time when the darkness of solitude challenges the light of love. Will you let the love in, or remain lost in the shadows?

  DRAKKAR is nixe!’s most personal work, a reflection of his battles with depression, the weight of his past, and the temptation to give in to despair. It’s a reminder that even in the darkest times, there’s a strange beauty, a value found in the struggle—just as Drakkar Noir is coveted not for its scent, but for its identity.

# URL of your site (replace with your actual domain or leave it as default for GitHub Pages)
url: "https://username.github.io"

# Optional: You can add other configurations like author, social links, etc.
author: Nixe
social_links:
  - name: Instagram
    url: "https://www.instagram.com/officialnixe"
  - name: Linktree
    url: "https://linktr.ee/officialnixe"
